version: "3.9"

volumes:
  mysql-prod-data:

services:
  #### react local prod build ####
  react-prod:
    build:
      context: ppsus-ears-react
      dockerfile: Dockerfile
    restart: always
    ports:
      - "${REACT_PORT}:80"
    environment:
      REACT_APP_PROJECT_NAME: "${PROJECT_NAME}"
      REACT_APP_SERVER_URL: "node-prod"
      REACT_APP_HOST_NAME: "${HOST_NAME}"
    depends_on:
      - node-prod
    networks:
      - ppsus_net

  #### node local prod ####
  node-prod:
    build:
      context: ppsus-ears-node
      dockerfile: Dockerfile
    restart: always
    ports:
      - "${NODE_PORT}:${NODE_PORT}"
    environment:
      SERVER_NAME: "${PROJECT_NAME}"
      SERVER_HOST: "${HOST_NAME}"
      SERVER_PORT: "${NODE_PORT}"
      JWT_SECRET: "${JWT_SECRET}"
      TYPEORM_CONNECTION: "mysql"
      TYPEORM_HOST: "mysql-prod"
      TYPEORM_DATABASE: "${DATABASE_NAME}"
      TYPEORM_USERNAME: "${DATABASE_USER}"
      TYPEORM_PASSWORD: "${DATABASE_PASSWORD}"
      TYPEORM_ENTITIES: "src/entity/**/*.js"
      TYPEORM_ENTITIES_DIR: "src/entity"
      TYPEORM_MIGRATIONS: "src/migration/**/*.js"
      TYPEORM_MIGRATIONS_DIR: "src/migration"
      TYPEORM_MIGRATIONS_RUN: "false"
      TYPEORM_SYNCHRONIZE: "false"
    depends_on:
      - mysql-prod
    networks:
      - ppsus_net

  ##### mysql local prod #####
  mysql-prod:
    image: mysql
    restart: always
    environment:
      MYSQL_HOST: "%"
      MYSQL_DATABASE: "${DATABASE_NAME}"
      MYSQL_USER: "${DATABASE_USER}"
      MYSQL_PASSWORD: "${DATABASE_PASSWORD}"
      MYSQL_ROOT_PASSWORD: "${DATABASE_PASSWORD}"
    volumes:
      - mysql-prod-data:/var/lib/mysql
    ports:
      - "${DATABASE_PORT}:3306"
    networks:
      - ppsus_net

networks:
  ppsus_net:
    driver: bridge
